version: "3.5"

services:

  php:
    build:
      context: docker/php
    ports:
    - 81:80
    volumes:
    - ./:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
    - 127.0.0.1:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cmsdb
    volumes:
    - ./databases/mysql5.7:/var/lib/mysql
